name: SonarCloud Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - preprod
      - dev

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pylint

      - name: Run Python tests and generate coverage report
        run: |
          pytest --cov=service --cov-branch --cov-report=xml:coverage.xml --cov-report=term || true
          

      - name: Run pylint (optional)
        run: |
          pylint . > pylint-report.txt || true
          cat pylint-report.txt

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=DeepChessIQ
            -Dsonar.organization=Steve8695
            -Dsonar.sources=.
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.exclusions=**/__pycache__/**,**/*.pyc,**/node_modules/**,**/build/**
            -Dsonar.verbose=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
